"""
feature_engineering.py

Preprocessing and feature engineering utilities.

Functions
---------
group_emp_title : Groups the raw emp_title column into high-level
                  professional categories using keyword-based semantic mapping
                  built from the 500 most frequent titles in the dataset.

Requirements
------------
    pip install pandas numpy
"""

import re
import numpy as np
import pandas as pd
from sklearn.preprocessing import RobustScaler


# ──────────────────────────────────────────────
# Constants
# ──────────────────────────────────────────────

PROFESSIONAL_CATEGORIES = [
    "Healthcare", "Education", "Tech", "Management", "Finance",
    "Legal", "Government", "Transportation", "Construction",
    "Sales", "Admin", "Hospitality", "Other", "Unknown",
]

# Order matters: more specific keywords first to avoid misclassification.
# E.g. 'sales manager' should hit 'Management' before 'Sales' if manager
# is listed first, so Sales-specific terms are checked before generic ones.
KEYWORD_MAPPING = [
    # Healthcare — checked first because terms are unambiguous
    (["registered nurse", "nurse practitioner", "rn case manager",
      "staff nurse", "nurse manager", "director of nursing",
      "registered nirse", "registered nurs"], "Healthcare"),
    (["nurse", "rn", "lpn", "lvn", "cna", "stna", "gna", "lna",
      "cma", "ccht", "chha", "lmt", "lcsw", "lmft"], "Healthcare"),
    (["physician assistant", "physician"], "Healthcare"),
    (["dentist", "dental hygienist", "dental hygientist", "dental hygenist",
      "dental assistant", "dental assitant", "dental asst",
      "dental lab technician", "dental lab tech", "dental tech",
      "dental assistance", "dental hygiene"], "Healthcare"),
    (["pharmacist", "pharmacy technician", "pharmacy tech", "pharm tech",
      "pharmacy", "cpht", "certified pharmacy tech"], "Healthcare"),
    (["physical therapist", "occupational therapist", "occupational therapy",
      "respiratory therapist", "respiratory therapy",
      "respiratory care practitioner", "massage therapist",
      "physical therapy", "physical therapy aide",
      "physical therapy technician"], "Healthcare"),
    (["medical assistant", "medical asst", "medical assitant",
      "med asst", "medical tech", "medical technician",
      "medical technologist", "medical laboratory technician",
      "medical laboratory technologist", "medical laboratory tech",
      "medical lab technician", "medical lab tech",
      "medical lab technologist", "medical laboratory tech",
      "medical biller", "medical coder", "medical billing",
      "medical records", "medical records tech",
      "medical records technician", "medical records coder",
      "medical transcriptionist", "medical transcription",
      "medical transcriber", "medical scribe", "medical physics",
      "medical physicist", "medical sonographer", "medical aesthetician",
      "medical esthetician", "medical writer", "medical editor",
      "medical dosimetrist", "medical support", "medical liaison",
      "medical science liaison", "medical interpreter",
      "medical billercoder", "medical coderbiller", "medical staff",
      "medical claims examiner", "medical supply technician",
      "medical resident"], "Healthcare"),
    (["radiologic technologist", "radiology technologist",
      "radiological technologist", "radiology tech",
      "radiology technician", "radiologic tech",
      "rad tech", "radiographer", "radiologist",
      "interventional radiology technologist"], "Healthcare"),
    (["sonographer", "cardiac sonographer", "cardiovascular sonographer",
      "vascular sonographer", "vascular technologist",
      "cardiovascular technologist", "cardiovascular tech",
      "cardiovascular technician", "echocardiographer", "echo tech",
      "diagnostic medical sonographer", "lead sonographer"], "Healthcare"),
    (["mri technologist", "mri tech", "mri technician", "mri",
      "ct technologist", "ct tech", "ct scan technologist",
      "cat scan technologist", "cat scan tech", "ctmri technologist",
      "petct technologist"], "Healthcare"),
    (["xray tech", "xray technologist", "xray technician",
      "x ray tech", "x ray technologist", "xray"], "Healthcare"),
    (["ultrasound tech", "ultrasound technologist", "ultrasound technician",
      "ultrasound", "ultra sound tech", "ultrasonographer",
      "mammographer", "mammography tech", "mammography technologist",
      "lead mammographer"], "Healthcare"),
    (["nuclear medicine technologist", "nuclear medicine tech",
      "nuclear medicine", "nuclear med tech"], "Healthcare"),
    (["phlebotomist", "phlebotomy", "lead phlebotomist"], "Healthcare"),
    (["surgical tech", "surgical technologist", "surgical technician",
      "certified surgical technologist", "certified surgical tech",
      "certified surgical technician", "cst", "scrub tech",
      "sterile processing tech", "sterile processing technician",
      "sterile tech", "spd tech", "or tech", "ob tech",
      "anesthesia tech", "anesthesia technician",
      "operating room technician"], "Healthcare"),
    (["paramedic", "emt", "emergency medical technician",
      "emergency medical tech", "first responder",
      "fire medic", "flight medic", "firemedic", "combat medic"], "Healthcare"),
    (["caregiver", "care giver", "care taker", "caretaker",
      "care provider", "home care", "home health aide", "home health aid",
      "home health", "home attendant", "home attendent",
      "home care aide", "home care aid", "home care provider",
      "home care giver", "home care worker", "home aid", "home help aid",
      "home help", "homecare", "homecare provider",
      "hha", "home health care", "home health care provider",
      "child care", "child care provider", "childcare",
      "childcare provider", "daycare provider", "day care provider",
      "direct care", "direct care worker", "direct care professional",
      "direct care staff", "direct care counselor",
      "direct support professional", "direct support staff",
      "direct support", "direct support provider",
      "direct service professional", "direct service provider",
      "personal care", "personal care aide", "personal care attendant",
      "personal care provider", "in home care provider",
      "care attendant", "care associate", "care advocate",
      "patient care", "patient care technician", "patient care tech",
      "patient care associate", "patient care advocate",
      "patient care representative", "patient transport",
      "patient transporter", "patient navigator", "patient advocate",
      "patient representative", "patient access", "patient access rep",
      "patient access associate", "patient access representative",
      "patient service", "patient service rep",
      "patient service associate", "patient service representative",
      "patient services", "patient services rep",
      "patient account", "patient account rep",
      "patient account representative", "patient accounts",
      "patient accounts rep", "patient finance",
      "patient registration", "patient registrar",
      "room attendant", "rehab aide", "rehab tech",
      "rehab technician", "rehabilitation counselor",
      "restorative aide", "therapy aide", "physical therapy aide"], "Healthcare"),
    (["caretaker", "catering", "dietary aide", "dietary worker",
      "dietary", "diet aide", "nutrition", "nutritionist",
      "dietitian", "registered dietitian", "clinical dietitian",
      "child nutrition", "nutrition services", "food service worker",
      "food services", "food service"], "Healthcare"),
    (["pca", "pct", "cna", "stna", "hha", "gna", "lna",
      "cma", "ccht", "chha", "lmt", "np", "pa",
      "pta", "cota", "rrt", "lpta", "dsp",
      "psychiatric technician", "psych tech",
      "behavioral health technician", "behavioral health tech",
      "behavior technician", "behavior interventionist",
      "behavioral interventionist", "behavioral technician",
      "registered behavior technician",
      "mental health technician", "mental health tech",
      "mental health worker", "mental health associate",
      "mental health professional", "mental health practitioner",
      "mental health therapy aide", "mental health clinician",
      "mental health counselor", "licensed mental health counselor",
      "qualified mental health professional",
      "psychiatric social worker", "clinical social worker",
      "licensed clinical social worker", "medical social worker",
      "school social worker", "senior social worker",
      "children social worker", "childrens social worker",
      "social work", "social service worker", "social services",
      "social welfare examiner", "caseworker", "case worker",
      "caseworker ii", "case management", "case aide",
      "case planner", "case manger"], "Healthcare"),
    (["audiologist", "optometrist", "optician", "licensed optician",
      "ophthalmic technician", "ophthalmic tech",
      "certified ophthalmic technician", "optometric technician",
      "optometric tech", "optical technician", "optical tech",
      "ophthalmologist", "optometric", "hygienist",
      "hearing aid dispenser"], "Healthcare"),
    (["veterinarian", "veterinary technician", "associate veterinarian",
      "vet tech", "veterinary tech", "licensed veterinary technician",
      "certified veterinary technician", "registered veterinary technician",
      "veterinarian technician", "vet technician", "vet asst",
      "veterinary"], "Healthcare"),
    (["psychologist", "school psychologist", "neurophysiologist",
      "psychiatrist", "anesthesiologist", "cardiologist",
      "radiologist", "neurologist", "orthopedic surgeon",
      "orthopaedic surgeon", "general surgeon", "surgeon",
      "pediatrician", "hospitalist", "epidemiologist",
      "pathologist", "podiatrist", "orthodontist",
      "physical science technician", "geologist", "biologist",
      "microbiologist", "embryologist", "physicist",
      "biostatistician", "exercise physiologist", "hydrologist",
      "hydrogeologist", "geophysicist", "marine surveyor",
      "marine biologist", "wildlife biologist", "agronomist",
      "horticulturist", "entomologist", "meteorologist",
      "epidemiologist", "toxicologist", "mortician",
      "anesthetist", "perfusionist", "cardiovascular perfusionist",
      "prosthetist", "orthotist", "audiologist",
      "cytotechnologist", "histotechnologist", "histotechnician",
      "histology technician", "histology tech", "histotech",
      "histologist", "cytogenetic technologist",
      "neurodiagnostic technologist", "polysomnographic technologist",
      "registered polysomnographic technologist",
      "sleep technologist", "sleep tech", "sleep technician",
      "eeg tech", "eeg technician", "eeg technologist",
      "telemetry tech", "telemetry technician",
      "cardiac tech", "cardiac monitor tech",
      "cardiac monitor technician", "cardiac technician",
      "cath lab tech", "cardiac cath lab technologist",
      "endoscopy tech", "endoscopy technician",
      "gi tech", "gi technician", "er tech", "er technician",
      "monitor tech", "monitor technician",
      "dialysis tech", "dialysis technician",
      "hemodialysis technician", "certified dialysis technician",
      "certified hemodialysis technician",
      "lab tech", "lab technician", "laboratory technician",
      "laboratory technologist", "lab technologist",
      "research technician", "research technologist",
      "research associate", "clinical research associate",
      "senior research associate", "sr research associate",
      "senior clinical research associate",
      "sr clinical research associate",
      "clinical research", "clinical tech", "clinical coder",
      "clinical liaison", "clinical dietitian",
      "chemist", "scientist", "researcher",
      "research and development", "biomed", "biomed tech",
      "biomedical technician", "biomedical equipment technician",
      "med tech", "medtech", "clinical laboratory technologist",
      "laboratory tech", "lab tec", "qc lab tech",
      "specimen processor", "pathologist",
      "speech language pathologist", "speech pathologist",
      "speech and language pathologist", "speechlanguage pathologist",
      "slp", "slpa", "occupational therapist",
      "occupational therapy"], "Healthcare"),
    (["social worker", "counselor", "school counselor",
      "guidance counselor", "admissions counselor",
      "career counselor", "vocational rehabilitation counselor",
      "licensed professional counselor", "substance abuse counselor",
      "residential counselor", "correctional counselor",
      "rehabilitation counselor", "rehab counselor",
      "addiction counselor", "chemical dependency counselor",
      "crisis counselor", "clinical counselor",
      "family counselor", "family service counselor",
      "investment counselor", "loan counselor",
      "housing counselor", "youth counselor",
      "resident counselor", "residence counselor",
      "program counselor", "intake counselor",
      "professional counselor", "college counselor",
      "academic counselor", "travel counselor",
      "senior counselor", "employment counselor",
      "enrollment counselor", "eap counselor",
      "genetic genetic counselor", "juvenile counselor",
      "correctional counselor", "educational counselor",
      "benefits counselor", "reimbursement counselor",
      "transition counselor", "vocational counselor",
      "community counselor", "mental health",
      "genetic counselor", "professional school counselor",
      "licensed mental health counselor",
      "high school counselor", "associate dean of students",
      "dean of students", "campus counselor",
      "behavioral health counselor"], "Healthcare"),

    # Education
    (["special education teacher", "teacher/coach",
      "instructional designer", "sr instructional designer",
      "senior instructional designer", "instructional coach",
      "instructional aide", "instructional facilitator",
      "instructional technologist"], "Education"),
    (["assistant professor", "associate professor"], "Education"),
    (["teacher", "profesor", "teachet", "teaher", "teaher",
      "tracher", "techer", "teach"], "Education"),
    (["professor", "instructor", "educator"], "Education"),
    (["assistant principal", "principal", "principle"], "Education"),
    (["superintendent", "superintendant", "superintedent",
      "superentendent", "super intendent", "super intendant",
      "supt"], "Education"),
    (["librarian", "library technician", "library tech",
      "library aide", "library associate"], "Education"),
    (["paraprofessional", "para professional", "parapro",
      "para"], "Education"),
    (["faculty", "lecturer", "adjunct", "adjunct lecturer",
      "senior lecturer", "associate dean", "associate dean of students",
      "dean", "dean of students", "academic dean",
      "dean of instruction", "dean of academic affairs",
      "associate provost", "provost", "vice provost",
      "vice chancellor", "headmaster", "head of school",
      "department chair", "dept chair", "program chair",
      "associate registrar", "registrar", "head tennis professional",
      "head golf professional", "golf professional",
      "tennis professional", "tennis pro", "golf pro"], "Education"),
    (["tutor", "coach", "instructional coach", "academic coach",
      "literacy coach", "math coach", "life coach",
      "job coach", "career coach", "health coach",
      "fitness professional", "personal trainer",
      "strength coach", "basketball coach", "football coach",
      "soccer coach", "head football coach", "head baseball coach",
      "head womens basketball coach",
      "head tennis professional", "head golf professional",
      "school aide", "school safety", "school safety agent",
      "bus monitor", "bus attendant", "bus aide",
      "substitute", "paraprofessional", "teaching fellow",
      "graduate student", "graduate researcher",
      "graduate student researcher", "research fellow",
      "phd student", "postdoc", "teaching artist",
      "special education", "educational diagnostician",
      "education technician", "education associate",
      "educational associate", "educational interpreter",
      "special education aide", "behavior interventionist",
      "instructional aide", "campus monitor",
      "behavior technician", "registered behavior technician"], "Education"),

    # Legal
    (["associate attorney", "attorney", "counsel",
      "general counsel", "senior counsel", "associate counsel",
      "corporate counsel", "inhouse counsel", "legal counsel",
      "senior corporate counsel", "senior legal counsel",
      "special counsel", "managing counsel",
      "associate general counsel", "asst general counsel"], "Legal"),
    (["paralegal", "legal assistant", "legal secretary",
      "legal asst", "legal assitant", "legal word processor",
      "legal support", "legal assistance",
      "legal instrument examiner", "legal instruments examiner",
      "para legal", "legal technician"], "Legal"),
    (["special agent", "investigator", "detective",
      "federal agent", "federal law enforcement",
      "federal air marshal", "federal bureau of investigation",
      "immigration enforcement agent", "enforcement agent",
      "border patrol", "border patrol agent", "us border patrol",
      "us border patrol agent", "patrol agent",
      "customs and border protection",
      "us customs and border protection",
      "immigration", "cbpo"], "Legal"),
    (["lawyer", "associate lawyer", "magistrate", "magistrate judge",
      "judge", "circuit judge", "associate judge", "district judge",
      "county judge", "superior court judge", "court reporter",
      "official court reporter", "freelance court reporter",
      "court stenographer", "court interpreter", "court liaison",
      "public defender", "prosecutor", "lobbyist",
      "bailiff", "commissioner", "warden", "probation",
      "probation officer", "probation agent", "parole agent",
      "adjudicator", "arbitrator", "mediator"], "Legal"),

    # Government & Law Enforcement
    (["police sergeant", "police officer", "police sgt",
      "police office", "police sargent", "police chief",
      "police corporal", "police commander",
      "police department", "policeman", "patrolman",
      "police recruit", "nypd", "lapd"], "Government"),
    (["correctional officer", "corrections officer",
      "correction officer", "correctional sgt",
      "correctional corporal", "correctional counselor",
      "corrections", "department of corrections",
      "dept of corrections", "cdcr",
      "federal bureau of prisons", "prison guard"], "Government"),
    (["deputy sheriff", "deputy", "sheriff", "undersheriff",
      "chief of police", "police"], "Government"),
    (["firefighter", "fire fighter", "fireman", "fire marshal",
      "fire chief", "asst fire marshal", "fire alarm technician",
      "fire alarm tech", "fire tech", "battalion chief",
      "fire battalion chief", "fire medic", "firemedic",
      "flight chief"], "Government"),
    (["sergeant", "sgt", "ssgt", "ssg", "ssg e", "staff sgt",
      "staff sargeant", "staff sargent", "smsgt", "msgt",
      "tsgt", "gysgt", "sfc", "ssgt", "sargeant", "sargent"], "Government"),
    (["lieutenant", "lt", "lt col", "lt colonel",
      "ltc", "lcdr", "lcpo"], "Government"),
    (["captain", "capt", "captian"], "Government"),
    (["corporal", "cpl", "specialist", "spc", "pvt",
      "private", "airman", "senior airman", "sailor",
      "seaman", "able seaman", "able bodied seaman",
      "marine", "infantry", "infantryman", "soldier",
      "enlisted", "active duty", "medic", "corpsman",
      "hospital corpsman", "combat medic", "crewmember",
      "inflight crewmember", "loadmaster", "aviator",
      "flight crew", "flight service"], "Government"),
    (["us army", "united states army", "army", "usarmy",
      "department of the army", "dept of army",
      "army national guard", "us navy", "united states navy",
      "navy", "usn", "department of the navy", "dept of the navy",
      "us air force", "united states air force", "usaf",
      "air force", "us marine corps", "united states marine corps",
      "usmc", "us coast guard", "united states coast guard",
      "uscg", "military", "armed forces",
      "department of defense", "dept of defense", "dod",
      "department of defense dod",
      "national guard", "reserve"], "Government"),
    (["mail carrier", "letter carrier", "mail handler",
      "mailhandler", "mail processor", "mail man", "mailman",
      "postal worker", "us postal service", "u s postal service",
      "usps", "us post office", "post office",
      "united states postal service", "united states post office",
      "united parcel service", "postmaster", "post master"], "Government"),
    (["security officer", "security guard", "security",
      "armed guard", "surveillance", "loss prevention",
      "loss prevention agent", "loss prevention associate",
      "asset protection", "asset protection agent",
      "asset protection associate", "school safety agent",
      "tso", "tsa", "park ranger", "ranger",
      "district ranger", "forest ranger",
      "state trooper", "trooper", "trooper ii", "master trooper",
      "highway patrol", "traffic agent",
      "traffic enforcement agent",
      "public safety", "public safety telecommunicator",
      "guard", "securitas"], "Government"),
    (["officer", "deputy", "warden", "trooper",
      "detective", "investigator", "agent",
      "law enforcement", "border patrol"], "Government"),

    # Transportation
    (["truck driver", "truck drive", "truck diver", "truck drivet",
      "truck dirver", "truck loader", "trucker", "trucking",
      "tractor trailer", "otr"], "Transportation"),
    (["delivery driver", "delivery", "courier", "messenger",
      "chauffeur", "chauffer", "car hauler",
      "shuttle driver", "valet", "valet parking",
      "valet attendant", "valet attendant"], "Transportation"),
    (["bus driver", "bus operator", "bus operater",
      "bus maintainer", "bus person", "bus aide",
      "bus monitor", "bus attendant"], "Transportation"),
    (["flight attendant", "flight attendent", "inflight",
      "cabin crew", "flight crew", "ramp agent",
      "ramp service", "ramp service agent", "ramp serviceman",
      "ramp lead", "ramp services", "ramp",
      "fleet service", "fleet service agent",
      "ground operations", "ground ops", "airport operations",
      "passenger service agent", "skycap",
      "station agent", "ticket agent", "gate agent",
      "cargo agent", "import agent", "air export agent",
      "dangerous goods agent", "load planner",
      "loadmaster", "fueler", "fuel handler",
      "aircraft technician", "aircraft worker", "aircraft mech",
      "aircraft maintainer", "avionics technician",
      "avionics tech", "avionics lead", "avionics",
      "aviation tech", "aviation technician", "aviation",
      "air traffic controller", "air traffic control",
      "atc", "atcs"], "Transportation"),
    (["dispatcher", "dispatch", "dispacher"], "Transportation"),
    (["conductor", "trainman", "switchman", "yardmaster",
      "yard jockey", "yard master", "trackworker",
      "trackman", "track worker", "carman",
      "signal maintainer", "roadmaster", "trainmaster",
      "locomotive engineer"], "Transportation"),
    (["pilot", "aviator", "navigator", "co pilot"], "Transportation"),
    (["driver", "motorman", "motor man", "motor hand",
      "motorhand", "hostler", "linehaul", "line haul",
      "trucker", "transporter", "transport",
      "delivery"], "Transportation"),
    (["longshoreman", "longshoremen", "longshoremen",
      "dockworker", "dock worker", "dockman",
      "deckhand", "deck hand", "able seaman",
      "boatswains mate", "merchant mariner",
      "merchant marine", "mate"], "Transportation"),

    # Construction & Trades
    (["maintenance supervisor", "maintenance technician",
      "maintenance manager", "maintenance tech",
      "maint tech", "maint mech", "maintance tech",
      "maintence tech", "maintanance", "maintanence",
      "maintainance", "maintainence", "maintenace",
      "maintaince", "mainteance", "maintanace",
      "maint", "maintance", "maintanence",
      "maintenence", "maintnance", "maintance worker",
      "maitenance tech", "maitenance", "maitainance",
      "maintaiance", "maintaianance", "maitainence",
      "maintaince", "maintainace", "maintenece",
      "maintenace worker", "maint worker"], "Construction"),
    (["service technician", "service tech", "service tec",
      "service teck", "service man", "serviceman",
      "service member"], "Construction"),
    (["production supervisor", "production"], "Construction"),
    (["machine operator", "machine op", "machine oper",
      "machine opperator", "machine operater",
      "machine operation", "machine opertor",
      "machine tender", "machine adjuster",
      "machine repair", "machine repairman",
      "machine setup", "machine set up",
      "machine tech", "machine builder",
      "machine attendant", "machining",
      "machining tech", "cnc tech", "cnc technician",
      "cnc programer", "cnc machinest", "cnc"], "Construction"),
    (["electrician", "electrican", "electritian",
      "electricain", "electrition", "eletrician",
      "electrian", "electrical apprentice",
      "electrical worker", "electrical tech",
      "electrical lead", "electrical designer",
      "electrical planner", "electrical technician",
      "electronics technician", "electronics tech",
      "electronic technician", "electronic tech",
      "electronics"], "Construction"),
    (["carpenter", "carpinter", "carpintero", "carpentry",
      "cabinetmaker", "cabinet maker", "cabinet builder",
      "millwright", "milwright", "mill wright",
      "millright", "millworker", "mill worker"], "Construction"),
    (["plumber", "plumbing", "plumbing pro", "plumbing technician",
      "plumbing designer", "steamfitter", "steam fitter",
      "pipefitter", "pipe fitter", "pipe layer", "pipelayer",
      "pipe designer", "lead piping designer",
      "union pipefitter", "sprinkler fitter",
      "gas fitter", "hvac", "hvac tech", "hvac technician",
      "hvacr tech", "hvacr technician", "refrigeration tech",
      "refrigeration technician", "ac technician", "ac tech",
      "appliance technician", "appliance tech"], "Construction"),
    (["welder", "welding", "ironworker", "iron worker",
      "steel worker", "steelworker", "sheet metal",
      "sheet metal worker", "sheetmetal worker",
      "boilermaker", "boiler maker", "rigger",
      "pipefitter", "pipe fitter", "millwright",
      "fabricator", "metal fabricator", "fabrication",
      "fabrication technician", "lead fabricator"], "Construction"),
    (["mechanic", "mechanic ", "mecanic", "machanic",
      "mech", "auto technician", "automotive technician",
      "auto tech", "auto technition", "automotive tech",
      "autobody technician", "auto body tech",
      "auto body technician", "body technician",
      "body tech", "body man", "bodyman", "body shop",
      "bodyshop", "collision tech", "collision technician",
      "collision repair technician", "collision repair tech",
      "auto damage adjuster", "auto damage appraiser",
      "auto appraiser", "auto adjuster",
      "auto glass technician", "lube tech", "lube technician",
      "tire tech", "tire technician", "tire builder",
      "wheel alignment", "alignment tech",
      "diesel tech", "diesel technician"], "Construction"),
    (["machinist", "machinest", "machinst", "machinest",
      "machanic", "machining", "cnc machinist",
      "cnc machinest", "toolmaker", "tool maker",
      "tool and die", "tool and die maker",
      "tool  die maker", "die maker", "die cutter",
      "die setter", "mold maker", "moldmaker",
      "mold tech", "mold technician", "grinder",
      "tooling", "tool builder", "tool designer",
      "tool tech", "tool room", "tool grinder",
      "tool pusher", "toolpusher", "driller",
      "directional driller", "derrick hand",
      "derrickhand", "derrickman", "derrick man",
      "rig hand", "roustabout", "roughneck",
      "floor hand", "floorhand", "motor hand",
      "motorhand", "floor man", "floorman",
      "derrick man", "driller"], "Construction"),
    (["installer", "install tech", "install technician",
      "installation tech", "installation technician",
      "installation", "lineman", "line man", "linemen",
      "lineworker", "line worker", "groundman",
      "groundsman", "grounds keeper", "groundskeeper",
      "groundsmen", "arborist", "tree trimmer",
      "landscaper", "landscaping", "landscape",
      "grounds", "groundskeeper", "irrigation tech",
      "irrigation technician"], "Construction"),
    (["laborer", "laberor", "labor", "skilled labor",
      "skilled trade", "skilled trades", "general labor",
      "general laborer", "labor worker", "skilled worker",
      "tradesman", "craftsman", "handyman", "handy man",
      "helper", "ranch hand", "farm hand", "farmhand",
      "farm worker", "farm labor", "farmer", "rancher",
      "miner", "underground miner", "coal miner",
      "diver", "commercial diver"], "Construction"),
    (["assembler", "assembly", "assembley", "assemble",
      "assembley", "assambler", "assember"], "Construction"),
    (["painter", "paint tech", "paint shop", "paint",
      "drywall", "drywall finisher", "drywall taper",
      "plasterer", "plaster", "taper", "finisher",
      "concrete finisher", "cement mason", "cement finisher",
      "mason", "brick mason", "brick layer",
      "bricklayer", "tile setter", "glazier", "glazer",
      "roofer", "roofing", "framer", "carpenter",
      "cabinetmaker", "cabinet maker",
      "estimator", "estimater", "estimating",
      "inspector", "inspecter", "building official",
      "code enforcement", "plans examiner",
      "construction worker", "construction",
      "construction representative", "construction rep",
      "construction labor", "construction management",
      "construction manager", "construction superintendent",
      "construction superintendant", "field superintendant",
      "general superintendant", "project superintendent",
      "project superintendant"], "Construction"),
    (["contractor", "subcontractor", "independent contractor",
      "sole proprietor", "sole proprieter", "selfemployed",
      "self employed", "self", "freelancer", "freelance"], "Construction"),
    (["operator", "equipment operator", "equipment operater",
      "heavy equipment", "heavy equipment operater",
      "forklift", "fork lift", "crane operator",
      "craneman", "utility worker", "utility person",
      "utility tech", "utility technician",
      "utility porter", "utility man",
      "material handler", "material handeler",
      "materials handler", "material handling",
      "packer", "packager", "palletizer",
      "picker", "pickerpacker", "order picker",
      "order filler", "order puller", "order builder",
      "orderfiller", "order entry", "sorter",
      "loader", "unloader", "stacker", "stocker",
      "night stocker", "stock", "stocking",
      "receiving", "receiver", "reciever",
      "shipper", "shipping", "shipping lead",
      "shipping department", "shipping dept",
      "shipping and receiving", "shippingreceiving",
      "shipping  receiving", "shipping receiving",
      "shipping associate", "shipping manger",
      "distribution", "distribution associate",
      "distribution tech", "distribution technician",
      "distribution lead", "distribution mgr",
      "warehouse", "wharehouse", "wearehouse",
      "wearhouse", "dock", "dock worker", "dockworker",
      "dockman", "dock lead", "dock associate",
      "freight", "freight handler", "freight team",
      "freight associate", "freight forwarder",
      "package handler", "packages"], "Construction"),
    (["maintenance", "maintanance", "maintanence",
      "maintainance", "maintainence", "maintenace",
      "maintaince", "mainteance", "maintanace",
      "maint", "maintenence", "maintnance",
      "maintaiance", "maitainance", "maitainence",
      "maintainace", "maintenece",
      "maintenace", "maint", "maintaince",
      "maintainance", "maintainence",
      "maintanace", "maint worker",
      "custodian", "custodial", "custodial worker",
      "head custodian", "lead custodian",
      "night custodian", "senior custodian",
      "janitorial", "janitor", "jailer",
      "housekeeper", "housekeeping",
      "house keeping", "house keeper",
      "housecleaner", "house cleaner",
      "house person", "houseperson", "houseman",
      "cleaning", "cleaner", "cleaning tech",
      "cleaning service", "sanitation worker",
      "sanitation", "sanitation lead",
      "sanitarian", "environmental services",
      "environmental services aide",
      "enviromental services",
      "environmental service",
      "evs", "evs tech", "evs aide",
      "sanitor", "porter", "utility porter",
      "bellman", "doorman", "door man",
      "valet", "concierge", "lobby attendant",
      "room attendant", "room service",
      "laundry", "laundry aide", "laundry worker",
      "laundry attendant"], "Construction"),
    (["production", "assembly", "assembler",
      "production supervisor", "production manager",
      "manufacturing", "manufacturing tech",
      "manufacturing technician", "manufacturing lead",
      "manufacturing engineer", "manufacturing associate",
      "manufacturing planner", "manufacturer",
      "plant operations", "plant technician",
      "plant manger", "plant mgr",
      "quality control", "quality assurance",
      "quality tech", "quality technician",
      "qc tech", "qc technician", "qa tech",
      "qa technician", "qa tester", "qa lead",
      "qa associate", "qc", "qa", "qaqc",
      "quality lead", "quality leader",
      "quality management", "quality manager",
      "quality engineer", "quality inspector",
      "quality inspection", "quality assurance tech",
      "quality assurance lead", "quality assurance rep",
      "quality control tech", "quality control lead",
      "quality control technician",
      "quality assurance technician",
      "quality control reviewer",
      "senior quality technician"], "Construction"),

    # Finance — before Management to catch finance-specific titles
    (["chief financial officer", "director of finance",
      "finance director", "dir of finance",
      "finance mgr", "finance manger"], "Finance"),
    (["senior financial analyst", "financial analyst",
      "financial advisor", "financial"], "Finance"),
    (["budget analyst", "budget analysis", "budget technician",
      "credit analyst", "management analyst",
      "senior financial analyst", "senior business analyst",
      "program analyst", "business analysis",
      "business anaylst", "anaylst"], "Finance"),
    (["personal banker", "banker", "banking"], "Finance"),
    (["loan officer", "loan processor", "loan originator",
      "mortgage loan originator", "mortgage originator",
      "loan agent", "loan servicer", "loan servicing",
      "loan closer", "loan operations", "loan counselor",
      "loan processing", "loan representative",
      "mortgage processor", "mortgage closer",
      "mortgage loan closer", "mortgage lender",
      "mortgage professional", "mortgage associate",
      "escrow", "escrow agent", "escrow closer",
      "escrow processor", "title agent", "title examiner",
      "title searcher", "title processor",
      "real estate closer", "real estate agent",
      "real estate associate", "real estate investor",
      "real estate appraiser", "commercial real estate appraiser",
      "senior appraiser", "staff appraiser",
      "field appraiser", "field examiner",
      "field agent", "appraiser", "auto appraiser",
      "auto damage appraiser", "property adjuster",
      "property appraiser", "residential appraiser",
      "commercial appraiser", "staff appraiser",
      "chief appraiser", "real property appraiser",
      "general adjuster", "independent adjuster",
      "liability adjuster", "casualty adjuster",
      "insurance adjuster", "auto damage adjuster",
      "bodily injury adjuster", "claims adjuster",
      "claims adjustor", "claim adjuster",
      "senior adjuster", "claims examiner",
      "claims representative", "claims rep",
      "claims processor", "claims professional",
      "claims technical expert", "claim examiner",
      "claim representative", "claim processor",
      "claim professional", "claim rep",
      "claims examiner ii", "sr claims examiner",
      "senior claims examiner", "senior claims representative",
      "senior claim representative", "sr claims representative",
      "sr claim representative",
      "insurance agent", "insurance rep", "insurance representative",
      "insurance verifier", "insurance verification",
      "insurance biller", "insurance billing",
      "insurance processor", "insurance examiner",
      "licensed agent", "independent agent", "career agent",
      "general agent", "associate agent", "senior agent",
      "field agent", "lead agent", "travel agent",
      "corporate travel agent", "leasing agent",
      "rental agent", "reservations agent",
      "reservation agent", "reservationist",
      "guest service agent", "guest services agent",
      "front desk agent", "station agent",
      "ramp agent", "cargo agent",
      "right of way agent", "land agent",
      "extension agent", "county extension agent",
      "business agent", "union representative",
      "union rep", "registered representative",
      "registered rep", "member service representative",
      "member service rep", "member services representative",
      "member services rep", "member services",
      "member service", "member service associate",
      "member advocate", "insurance producer",
      "enrolled agent", "revenue agent",
      "tax examiner", "tax senior", "tax associate",
      "tax senior associate", "tax professional",
      "tax technician", "tax preparer", "tax processor",
      "tax staff", "tax pro", "tax assessor",
      "tax examining technician", "tax senior",
      "lead tax examiner", "senior tax associate",
      "patent examiner", "patent attorney",
      "disability examiner", "disability claims adjudicator",
      "disability adjudicator", "bank examiner",
      "national bank examiner", "revenue examiner",
      "social welfare examiner", "legal instrument examiner",
      "legal instruments examiner", "voucher examiner",
      "claims examiner", "senior examiner",
      "sr examiner", "examiner", "adjudicator",
      "benefit authorizer", "actuary", "associate actuary",
      "economist", "senior economist", "statistician",
      "senior statistician", "mathematical statistician",
      "biostatistician", "trader", "equity trader",
      "energy trader", "senior trader",
      "portfolio manager", "relationship manager",
      "investment adviser", "investment advisor",
      "investment professional", "investment associate",
      "investment representative", "investment banking associate",
      "registered client associate",
      "registered client service associate",
      "senior registered associate",
      "senior registered client associate",
      "senior client associate", "client associate",
      "client service associate", "client services associate",
      "paraplanner", "wealth management associate",
      "commercial lender", "consumer lending",
      "commercial lending", "lender",
      "mortgage", "escrow", "title",
      "underwriting", "underwriting asst",
      "underwriting associate"], "Finance"),
    (["portfolio manager", "relationship manager"], "Finance"),
    (["claims adjuster", "underwriter", "broker"], "Finance"),
    (["staff accountant", "senior accountant", "accountant",
      "accounant", "acountant", "accoutant", "acct",
      "bookeeper", "bookkeeper", "book keeper",
      "bookkeeping", "bookkepper"], "Finance"),
    (["auditor", "audit associate", "audit senior",
      "senior audit associate", "assurance associate",
      "assurance senior", "senior assurance associate",
      "cpa", "comptroller", "controller",
      "assistant controller", "accounts payable",
      "accounts receivable", "account receivable",
      "account receivables", "accounts receivables",
      "accounts receivable rep", "ar rep", "ar",
      "accts payable", "accts receivable",
      "billing", "billing rep", "billing lead",
      "billing associate", "billing department",
      "billing dept", "billing processor",
      "biller", "senior biller", "insurance biller",
      "medical biller", "medical coder",
      "medical billercoder", "medical coderbiller",
      "medical biller and coder", "certified coder",
      "certified professional coder", "inpatient coder",
      "outpatient coder", "remote coder",
      "remote medical coder", "coder", "coder ii",
      "coder iii", "clinical coder", "payroll",
      "payroll tech", "payroll technician",
      "payroll processor", "payroll associate",
      "payrollhr", "hrpayroll"], "Finance"),
    (["teller", "broker", "finance", "accounting",
      "contract specialist", "buyer", "planner",
      "procurement", "purchasing", "purchaser",
      "purchasing agent", "purchasing buyer",
      "purchasing mgr", "procurement agent",
      "procurement forester", "procurement lead",
      "procurement technician", "associate buyer",
      "senior buyer", "sr buyer", "buyer ii",
      "buyer iii", "buyer planner", "buyerplanner",
      "plannerbuyer", "mro buyer", "pharmacy buyer",
      "media buyer", "corporate buyer",
      "supply chain", "supply chain planner",
      "supply chain mgr", "supply chain management",
      "logistics", "logistician", "logistics mgr",
      "logistics lead", "logistics tech",
      "logistics technician", "logistics planner",
      "logistics management", "logistics support",
      "logistics associate", "logistics chief",
      "logistics nco", "supply planner",
      "demand planner", "material planner",
      "materials planner", "supply tech",
      "supply nco", "supply sgt",
      "inventory", "inventory control",
      "inventory management", "inventory control lead",
      "inventory lead", "inventory planner",
      "inventory associate", "inventory tech",
      "inventory tech", "material control",
      "materials management", "materials handler",
      "material management", "material handling",
      "receiving", "receiving lead", "receiving associate",
      "receiving checker"], "Finance"),
    (["financial", "finance", "accounting", "accounts",
      "bookkeeping", "payroll", "treasury",
      "treasurer", "comptroller", "controller",
      "risk management", "compliance",
      "compliance associate", "regulatory compliance",
      "regulatory affairs", "credit",
      "credit rep", "credit mgr",
      "collections", "collection", "collections agent",
      "collection agent", "collections rep",
      "collection rep", "collections representative",
      "collection representative",
      "credit  collections", "collections associate",
      "claims associate", "loss mitigation",
      "billing", "invoicing", "account",
      "accounts", "acct", "acct mgr",
      "acct rep", "acct exec", "acct tech",
      "account tech", "account manger",
      "account liaison", "account associate",
      "account services", "account management",
      "account service rep",
      "account service representative",
      "account representative",
      "account payable", "account receivable",
      "account receivables"], "Finance"),

    # Management — broad terms last within this block
    (["chief operating officer", "chief executive",
      "chief marketing officer", "cmo",
      "chief of staff", "chief of operations",
      "chief of police", "operations chief",
      "division chief", "section chief",
      "branch chief", "bureau chief",
      "battalion chief", "fire battalion chief",
      "squad leader", "unit chief", "team chief",
      "crew chief", "crew cheif", "crewleader",
      "crew leader", "lead person", "leadperson",
      "leadman", "lead man", "crew lead",
      "group leader", "group lead", "dept lead",
      "department lead", "section leader",
      "section head", "department head",
      "department mgr", "dept head",
      "dept mgr", "general managet",
      "general manger", "general manager "], "Management"),
    (["chief operating officer", "chief financial officer",
      "chief executive"], "Management"),
    (["senior vice president", "assistant vice president",
      "vice president", "vice pres"], "Management"),
    (["executive director", "managing director",
      "associate director", "assistant director"], "Management"),
    (["director of operations", "director of sales",
      "director of marketing", "director of it",
      "director of business development",
      "director of human resources",
      "dir of operations", "dir of finance"], "Management"),
    (["regional director", "senior director",
      "creative director", "marketing director",
      "program director"], "Management"),
    (["assistant general manager", "asst gm",
      "assistant store manager", "asst store mgr"], "Management"),
    (["vp of operations", "vp sales"], "Management"),
    (["ceo", "cfo", "coo", "cto", "svp", "cio", "cso",
      "cco", "cpo", "cao", "cro", "ciso"], "Management"),
    (["owner/operator", "managing partner", "cofounder",
      "sole member", "franchisee", "proprietor",
      "independent distributor", "landlord",
      "shareholder", "investor"], "Management"),
    (["senior project manager", "sr. project manager",
      "sr project mgr"], "Management"),
    (["senior manager", "sr. manager", "sr manager",
      "sr mgr"], "Management"),
    (["operations manager", "general manager", "office manager",
      "store manager", "branch manager", "district manager",
      "regional manager", "area manager", "department manager",
      "account manager", "assistant manager", "business manager",
      "plant manager", "warehouse manager", "property manager",
      "service manager", "project manager", "program manager",
      "product manager", "marketing manager", "territory manager",
      "practice manager", "production manager",
      "engineering manager", "human resources manager",
      "hr manager", "finance manager", "accounting manager",
      "customer service manager", "logistics manager",
      "purchasing manager", "quality manager",
      "facilities manager", "facility manager",
      "site manager", "parts manager",
      "office manger", "office manage",
      "office mananger", "office managet",
      "office mgr", "office mngr",
      "store manger", "store mgr",
      "store manager", "branch manger",
      "branch mgr", "district mgr",
      "regional mgr", "area mgr",
      "territory mgr", "territory manger",
      "territory manager", "business mgr",
      "business manger", "business manager",
      "plant mgr", "plant manger",
      "property mgr", "property manger",
      "property management", "project mgr",
      "project manger", "program mgr",
      "program manger", "product mgr",
      "marketing mgr", "logistics mgr",
      "operations mgr", "operations manger",
      "operations manager", "ops mgr",
      "parts mgr", "parts dept",
      "shipping mgr", "shipping manger",
      "distribution mgr", "fleet mgr",
      "fleet manager", "supply chain mgr",
      "account mgr", "acct mgr",
      "finance mgr", "finance manger",
      "credit mgr", "it mgr", "it manger",
      "it manager", "deli mgr",
      "bakery mgr", "grocery mgr",
      "produce mgr", "department mgr",
      "dept mgr", "department manager",
      "service mgr", "service manger",
      "sr mgr", "senior mgr",
      "asst mgr", "asst manger",
      "asst manager", "asst gm",
      "general mgr", "gen mgr",
      "district leader", "operations leader",
      "market leader", "store leader",
      "project leader", "program leader",
      "business leader", "senior leader",
      "area leader", "section leader",
      "unit leader", "team leader",
      "zone leader", "shift leader",
      "shift lead", "line leader",
      "quality lead", "quality leader",
      "lead", "team lead", "tech lead",
      "technical lead", "technology lead",
      "design lead", "project lead",
      "senior lead", "lead agent",
      "operations lead", "shipping lead",
      "line lead", "manufacturing lead",
      "procurement lead", "logistics lead",
      "support lead", "service desk lead",
      "back office lead", "account lead",
      "inventory lead", "receiving lead",
      "billing lead", "qa lead",
      "quality assurance lead",
      "quality control lead",
      "senior project lead", "sr project leader",
      "it project leader", "it project lead",
      "program lead", "process lead",
      "distribution lead", "dock lead",
      "cell lead", "line lead",
      "department lead", "dept lead",
      "crew lead", "group lead",
      "section lead"], "Management"),
    (["president", "owner", "partner", "executive",
      "managing partner", "owner/operator",
      "gm", "managing member",
      "managing editor", "managing director",
      "managing agent", "managing counsel",
      "managing partner"], "Management"),
    (["team leader", "team lead", "foreman", "forman",
      "formen", "foremen", "foreperson",
      "supervisor", "superviser", "supervior",
      "supevisor", "supervisior", "supervision",
      "supervise", "super visor", "super",
      "suoervisor", "suoervisor", "supervison",
      "supervisior", "mgr", "mngr", "mgmt",
      "management", "managment", "managaer",
      "managet", "maneger", "maneger",
      "manger", "manage", "managaer",
      "mannager", "mamager", "menager",
      "mananger", "mananger", "mnager",
      "managee", "mnager", "onwer", "ower",
      "owener", "owne", "ownee", "qwner",
      "ownet", "wner", "owne", "onwer"], "Management"),
    (["director", "dir"], "Management"),
    (["manager", "mgr", "mngr"], "Management"),
    (["vp", " vp"], "Management"),

    # Tech
    (["senior software engineer", "software engineer",
      "software developer"], "Tech"),
    (["network engineer", "network administrator"], "Tech"),
    (["systems engineer", "system engineer",
      "systems analyst", "system analyst",
      "systems administrator", "system administrator",
      "system integrator"], "Tech"),
    (["programmer analyst", "programmer", "programer"], "Tech"),
    (["web developer", "web designer", "web design",
      "web editor", "web producer", "webmaster",
      "web design"], "Tech"),
    (["data analyst", "business analyst", "senior business analyst",
      "program analyst", "business analysis",
      "business anaylst"], "Tech"),
    (["it manager", "it specialist", "it director", "it analyst",
      "it consultant", "it project manager", "it support",
      "it support tech", "it tech support", "it helpdesk",
      "it help desk", "it desktop support", "it technical support",
      "it operations", "it department", "it management",
      "it associate", "it professional", "it field technician",
      "it tech", "it manger", "it spec", "it lead",
      "it support technician", "desktop support",
      "desktop support tech", "desktop support technician",
      "desktop technician", "help desk", "help desk tech",
      "help desk technician", "helpdesk", "helpdesk technician",
      "technical support", "tech support", "tech support rep",
      "support tech", "computer support",
      "computer tech", "computer technician",
      "computer programer", "pc tech", "pc technician",
      "noc tech", "noc technician", "it tech",
      "application support", "desktop support",
      "information technology", "information technologist",
      "information technician", "information tech"], "Tech"),
    (["electrical engineer", "mechanical engineer", "civil engineer",
      "manufacturing engineer", "quality engineer",
      "design engineer", "field engineer",
      "field service engineer", "project engineer",
      "chief engineer", "senior engineer",
      "engineering manager", "quality engineer",
      "systems engineer", "civil engineer",
      "structural engineer", "aerospace engineer",
      "chemical engineer", "industrial engineer",
      "process engineer", "controls engineer",
      "automation engineer", "software engineer",
      "test engineer", "reliability engineer",
      "environmental engineer"], "Tech"),
    (["air traffic controller", "air traffic control",
      "atc", "atcs"], "Tech"),
    (["chemist", "scientist", "architect",
      "engineer", "analyst",
      "drafter", "draftsman", "drafting",
      "cad tech", "cad drafter", "cad designer",
      "cad technician", "cadd technician",
      "design drafter", "drafterdesigner",
      "designerdrafter", "structural designer",
      "piping designer", "electrical designer",
      "civil designer", "lead piping designer",
      "sr electrical designer",
      "senior electrical designer",
      "senior cad designer",
      "senior designer", "designer",
      "graphic designer", "graphic design",
      "graphic artist", "sr graphic designer",
      "senior graphic designer",
      "sr graphic designer",
      "instructional designer",
      "interaction designer",
      "interactive designer",
      "product designer", "industrial designer",
      "interior designer", "interior design",
      "landscape designer", "lighting designer",
      "fashion designer", "floral designer",
      "kitchen designer", "textile designer",
      "web designer", "ux designer",
      "ui ux designer", "uiux designer",
      "senior ux designer", "sr ux designer",
      "user experience designer",
      "senior user experience designer",
      "experience designer",
      "digital designer", "visual designer",
      "senior visual designer",
      "senior interior designer",
      "associate designer",
      "design associate", "creative designer",
      "lead designer", "lead esthetician",
      "tool designer", "system designer",
      "cad designer", "cad tech",
      "senior graphic designer",
      "sound designer", "game designer",
      "technical designer", "technical writer",
      "senior technical writer",
      "sr technical writer",
      "tech writer", "staff writer",
      "grant writer", "copy editor",
      "medical writer", "content writer",
      "senior writer", "editor",
      "senior editor", "associate editor",
      "managing editor", "editor in chief",
      "editorinchief", "film editor",
      "video editor", "photo editor",
      "sports editor", "technical editor",
      "web editor", "medical editor",
      "content editor", "writerproducer",
      "producereditor", "proofreader",
      "copywriter", "senior copywriter",
      "proposal writer", "grant writer",
      "technical writer"], "Tech"),
    (["software", "developer", "programmer", "network",
      "systems", "data ", "cto", "scrum master",
      "agile coach", "product management",
      "product development", "digital marketing",
      "social media", "marketing strategist",
      "digital strategist", "content strategist",
      "seo", "web", "digital", "analytics",
      "database", "dba", "oracle dba", "sr dba",
      "senior dba", "sql dba",
      "technologist", "information technology"], "Tech"),

    # Sales & Retail
    (["regional sales manager", "district sales manager",
      "sales manager"], "Sales"),
    (["senior account executive", "account executive"], "Sales"),
    (["senior account manager"], "Sales"),
    (["sales representative", "sales rep", "sales consultant",
      "sales engineer", "sales executive", "sales director",
      "sales associate", "inside sales", "sale rep",
      "sale associate", "sale representative",
      "sale person", "saleman", "salesman"], "Sales"),
    (["business development manager",
      "director of business development"], "Sales"),
    (["business development"], "Sales"),
    (["realtor", "dealer", "merchandiser", "merchandizer",
      "merchandise", "merchandising", "merchant",
      "retail", "retail associate", "retail management",
      "retail mgr", "store associate", "store worker",
      "stock associate", "stocker", "night stocker",
      "stocking", "storekeeper", "storekeeper ii",
      "stockroom", "stockman", "produce associate",
      "deli associate", "deli worker", "bakery associate",
      "grocery", "grocery stocker", "grocery team member",
      "grocery mgr", "personal shopper",
      "loss prevention", "loss prevention agent",
      "loss prevention associate", "asset protection",
      "asset protection agent", "asset protection associate"], "Sales"),
    (["insurance agent", "insurance rep",
      "insurance representative", "insurance producer",
      "licensed producer", "licensed agent",
      "independent agent", "career agent",
      "general agent", "associate agent",
      "senior agent", "field agent",
      "lead agent", "travel agent",
      "leasing agent", "rental agent",
      "leasing professional"], "Sales"),
    (["cashier", "sales", "associate",
      "brand ambassador", "demonstrator",
      "entertainer", "promoter"], "Sales"),

    # Admin & Support
    (["administrative assistant", "admin assistant",
      "adm asst", "admin asst", "asst"], "Admin"),
    (["executive assistant", "exec asst",
      "executive assistant "], "Admin"),
    (["office administrator", "office assistant",
      "office asst", "office assitant",
      "office support", "office staff",
      "office personnel", "office worker",
      "office work", "office associate",
      "office services", "office assistance",
      "office management", "office manage",
      "office lead", "office tech",
      "office mngr", "office mgr",
      "office manger", "office mananger",
      "office managet", "office manage",
      "office mananger"], "Admin"),
    (["project coordinator", "program coordinator",
      "marketing coordinator", "case manager",
      "care manager", "case manger"], "Admin"),
    (["customer service representative",
      "customer service manager",
      "customer service rep", "customer service",
      "customer care", "customer care rep",
      "customer care representative",
      "customer care professional",
      "customer care associate",
      "customer care agent",
      "customer care advocate",
      "customer support", "customer support rep",
      "customer support representative",
      "customer support associate",
      "customer relations",
      "customer relations representative",
      "customer representative",
      "customer rep",
      "customer experience",
      "customer operations",
      "customer account rep",
      "customer account representative",
      "customer success",
      "cust service", "cust service rep",
      "costumer service", "customers service",
      "customer  service",
      "client services", "client service",
      "client service rep", "client service associate",
      "client services associate",
      "client services rep",
      "client services representative",
      "client service representative",
      "client representative",
      "client relations", "client support",
      "client advocate", "client liaison",
      "client associate",
      "member service representative",
      "member service rep", "member services representative",
      "member services rep", "member services",
      "member service", "member service associate",
      "member advocate",
      "contact representative", "contact rep",
      "call center", "call center rep",
      "call center agent",
      "call center representative",
      "call taker", "telemarketer",
      "csr", "customer svc"], "Admin"),
    (["human resources manager", "hr manager",
      "hr director", "hr specialist", "hr generalist",
      "human resources", "hr", "hr rep",
      "hr technician", "hr tech", "hr associate",
      "hr asst", "hr mgr", "hr nco", "hrbp",
      "hrm", "human resource", "human resource mgr",
      "human resource generalist",
      "talent acquisition", "recruiter",
      "staffing", "headhunter"], "Admin"),
    (["program specialist", "contract specialist",
      "program support", "program associate",
      "program integrator", "program manger",
      "program mgr", "program lead",
      "program aide", "program asst",
      "program technician", "program technician ii",
      "program monitor", "program management",
      "program manager"], "Admin"),
    (["consultant", "senior consultant",
      "it consultant", "management consultant",
      "business consultant", "senior consultant",
      "senior advisor", "advisor"], "Admin"),
    (["secretary", "receptionist", "clerk",
      "clerical", "accounting clerk",
      "office assistant", "office asst",
      "legal secretary", "legal asst",
      "administrative", "admin",
      "cleark", "clerck"], "Admin"),
    (["coordinator", "administrator", "recruiter",
      "trainer", "training", "training mgr",
      "training technician", "training nco"], "Admin"),
    (["specialist", "program specialist",
      "hr specialist", "hr generalist",
      "recruiter", "trainer", "advisor",
      "consultant", "senior consultant",
      "it consultant", "management",
      "administration", "admin",
      "csr", "assistant",
      "case manager", "case manger",
      "case planner", "care manager"], "Admin"),

    # Hospitality & Food
    (["executive chef", "chef", "head chef",
      "sous chef", "pastry chef"], "Hospitality"),
    (["bartender", "bar tender"], "Hospitality"),
    (["cook", "line cook", "prep cook",
      "lead cook", "head cook",
      "kitchen worker", "kitchen staff",
      "kitchen helper", "food runner",
      "food prep", "food handler",
      "dietary aide", "dietary worker",
      "dietary", "diet aide",
      "busser", "dishwasher", "dish washer",
      "food service worker", "food services",
      "food service", "food service leader",
      "food service associate", "food and beverage",
      "baker", "lead baker", "head baker",
      "bakery", "pastry", "brewer",
      "brewmaster", "head brewer",
      "sommelier", "winemaker", "barista",
      "catering", "caterer", "banquets",
      "banquet houseman"], "Hospitality"),
    (["server", "waiter", "waitress", "waitstaff",
      "wait staff", "hostess", "host",
      "busser", "food runner",
      "room service", "banquet server"], "Hospitality"),
    (["housekeeper", "housekeeping", "house keeping",
      "house keeper", "housecleaner", "house cleaner",
      "house person", "houseperson", "houseman",
      "room attendant", "laundry aide",
      "laundry worker", "laundry attendant",
      "laundry", "nanny", "babysitter",
      "baby sitter", "au pair",
      "dog walker", "dog groomer",
      "pet groomer", "pet stylist",
      "groomer", "kennel tech"], "Hospitality"),
    (["concierge", "bellman", "doorman", "door man",
      "valet", "valet parking", "valet attendant",
      "lobby attendant", "guest service",
      "guest services", "guest service agent",
      "guest services agent", "guest service rep",
      "guest service representative",
      "guest services representative",
      "guest relations", "casino host",
      "casino porter", "slot attendant",
      "slot technician", "slot floorperson",
      "table games", "gaming", "dealer",
      "entertainment", "entertainer"], "Hospitality"),

    # Other — catch-all for remaining known categories
    (["stylist", "hair stylist", "hairstylist",
      "hairdresser", "hair dresser",
      "cosmetologist", "cosmotologist",
      "cosmetology", "esthetician", "aesthetician",
      "nail tech", "nail technician", "nails tech",
      "nails technician", "manicurist",
      "master stylist", "senior stylist",
      "lead esthetician", "medical aesthetician",
      "medical esthetician", "makeup artist",
      "make up artist", "tattoo artist",
      "barber", "master barber",
      "beautician", "colorist",
      "hairstyles", "hairdresser"], "Other"),
    (["graphic designer", "designer", "editor",
      "producer", "marketing", "writer",
      "author", "journalist", "reporter",
      "correspondent", "news reporter",
      "news anchor", "broadcaster",
      "announcer", "radio host", "radio announcer",
      "photographer", "senior photographer",
      "news photographer", "videographer",
      "cinematographer", "animator",
      "musician", "singer", "dancer",
      "performer", "entertainer",
      "artist", "senior artist",
      "d artist", "vfx artist",
      "graphic artist", "teaching artist",
      "makeup artist", "tattoo artist",
      "chef", "cook", "baker",
      "catering", "caterer"], "Other"),
    (["pastor", "senior pastor", "lead pastor",
      "youth pastor", "campus pastor",
      "associate pastor", "worship pastor",
      "minister", "minister of music",
      "youth minister", "senior minister",
      "associate minister", "chaplain",
      "staff chaplain", "organist",
      "missionary", "clergy",
      "sexton", "priest", "rabbi",
      "preacher", "monk", "nun"], "Other"),
    (["technician", "tech", "specialist",
      "associate", "worker", "staff",
      "general", "professional",
      "consultant", "advisor",
      "representative", "rep",
      "agent", "coordinator",
      "operator", "processor",
      "handler", "attendant",
      "aide", "assistant",
      "helper", "support",
      "lead", "senior",
      "junior", "trainee",
      "apprentice", "intern",
      "volunteer", "member",
      "employee", "contractor",
      "freelancer", "self-employed"], "Other"),
]


# ──────────────────────────────────────────────
# Internal helpers
# ──────────────────────────────────────────────

def _normalize_titles(series: pd.Series) -> pd.Series:
    """
    Lowercase, strip whitespace and remove non-alphabetic characters.
    Collapses obvious variants like 'Teacher' / 'TEACHER' / 'teacher'.
    """
    return (
        series
        .str.lower()
        .str.strip()
        .str.replace(r"[^a-z\s]", "", regex=True)
        .str.strip()
    )


def _frequency_filter(series: pd.Series, min_freq: int) -> pd.Series:
    """
    Replace categories appearing fewer than min_freq times with 'Other'.
    Preserves NaNs.
    """
    freq = series.value_counts()
    rare = freq[freq < min_freq].index
    return series.apply(lambda x: "Other" if x in rare else x)


def _semantic_mapping(title: str) -> str:
    """
    Maps a normalized job title to a high-level professional category
    using keyword matching against KEYWORD_MAPPING.
    The first matching rule wins, so order in KEYWORD_MAPPING matters.
    Titles with no matching keyword are classified as 'Other'.
    NaNs are classified as 'Unknown'.
    """
    if pd.isna(title) or title == "":
        return "Unknown"
    t = title.lower().strip()
    for keywords, category in KEYWORD_MAPPING:
        if any(kw in t for kw in keywords):
            return category
    return "Other"


# ──────────────────────────────────────────────
# Main function
# ──────────────────────────────────────────────

def group_emp_title(
    df: pd.DataFrame,
    col: str = "emp_title",
    min_freq: int = 50,
    output_col: str = "emp_title_grouped",
) -> pd.DataFrame:
    """
    Full pipeline to group emp_title into high-level professional categories.

    Steps
    -----
    1. Normalize raw text (lowercase, strip, remove special characters).
    2. Frequency filter: titles appearing fewer than min_freq times → 'Other'.
    3. Keyword-based semantic mapping using KEYWORD_MAPPING.
    4. NaN imputation with 'Unknown'.

    Parameters
    ----------
    df         : DataFrame containing the raw emp_title column.
    col        : Name of the column to process (default 'emp_title').
    min_freq   : Titles appearing fewer than this number of times are
                 collapsed into 'Other' before mapping (default 50).
    output_col : Name of the new grouped column (default 'emp_title_grouped').

    Returns
    -------
    df with a new column `output_col`. The original column is preserved.
    """

    print(f"→ Step 1: Normalizing text in '{col}'...")
    normalized = _normalize_titles(df[col])
    print(f"  Unique titles before normalization : {df[col].nunique():,}")
    print(f"  Unique titles after normalization  : {normalized.nunique():,}")

    print(f"\n→ Step 2: Frequency filter (min_freq={min_freq})...")
    filtered = _frequency_filter(normalized, min_freq=min_freq)
    print(f"  Unique titles after frequency filter: {filtered.nunique():,}")

    print(f"\n→ Step 3: Applying keyword-based semantic mapping...")
    df[output_col] = filtered.apply(_semantic_mapping)

    # ── Summary ──────────────────────────────────────────────────────────
    print(f"\n✓ Done. Distribution of '{output_col}':")
    dist = (
        df[output_col]
        .value_counts()
        .rename_axis("category")
        .reset_index(name="n")
    )
    dist["pct"] = (dist["n"] / len(df) * 100).round(2)
    print(dist.to_string(index=False))

    return df

def clean_emp_length(x):
    if pd.isna(x):
        return 0
    x = str(x).strip()
    if x == "< 1 year":
        return 0.5
    if x == "10+ years":
        return 10
    return float(re.search(r"\d+", x).group())

def preprocess_features_LGD(df_train: pd.DataFrame, df_test: pd.DataFrame, 
                        categorical_features: list, numeric_features: list):
    """
    Applies RobustScaler fitted on train only, and One-Hot Encoding to both datasets.
    """
    # One-Hot Encoding — applied to both independently
    df_train = pd.get_dummies(df_train, columns=categorical_features, drop_first=True)
    df_test  = pd.get_dummies(df_test,  columns=categorical_features, drop_first=True)

    # Align columns in case get_dummies produces different columns
    df_train, df_test = df_train.align(df_test, join='left', axis=1, fill_value=0)

    # RobustScaler — fit on train only, transform both
    scaler = RobustScaler()
    df_train[numeric_features] = scaler.fit_transform(df_train[numeric_features])
    df_test[numeric_features]  = scaler.transform(df_test[numeric_features])

    return df_train, df_test, scaler

def preprocess_features_LGD(df_train: pd.DataFrame, df_test: pd.DataFrame,
                             categorical_features: list, numeric_features: list):
    """
    Applies RobustScaler fitted on train only and One-Hot Encoding to both datasets.
    Intended for LGD model preprocessing — trained on defaulted loans only.

    Parameters
    ----------
    df_train             : training set (cleaned via clean_features_LGD)
    df_test              : test set (cleaned via clean_features_LGD)
    categorical_features : list of categorical feature names to encode
    numeric_features     : list of numeric feature names to scale

    Returns
    -------
    df_train_processed, df_test_processed, scaler
    """
    from sklearn.preprocessing import RobustScaler

    # One-Hot Encoding — applied to both independently
    df_train = pd.get_dummies(df_train, columns=categorical_features, drop_first=True)
    df_test  = pd.get_dummies(df_test,  columns=categorical_features, drop_first=True)

    # Align columns in case get_dummies produces different columns
    df_train, df_test = df_train.align(df_test, join='left', axis=1, fill_value=0)

    # RobustScaler — fit on train only, transform both
    scaler = RobustScaler()
    df_train[numeric_features] = scaler.fit_transform(df_train[numeric_features])
    df_test[numeric_features]  = scaler.transform(df_test[numeric_features])

    return df_train, df_test, scaler